import { CSSProperties } from 'react';

export type BreakPoint = 'xs' | 'sm' | 'md' | 'lg' | 'xl';
export type StyleProp<Value> = Value | Partial<Record<BreakPoint | (string & {}), Value>>;
export type BasicProps = {
  m?: StyleProp<number | string>;
  my?: StyleProp<number | string>;
  mx?: StyleProp<number | string>;
  mt?: StyleProp<number | string>;
  mb?: StyleProp<number | string>;
  ml?: StyleProp<number | string>;
  mr?: StyleProp<number | string>;
  p?: StyleProp<number | string>;
  py?: StyleProp<number | string>;
  px?: StyleProp<number | string>;
  pt?: StyleProp<number | string>;
  pb?: StyleProp<number | string>;
  pl?: StyleProp<number | string>;
  pr?: StyleProp<number | string>;
  bg?: StyleProp<string>;
  c?: StyleProp<string>;
  opacity?: StyleProp<number>;
  w?: StyleProp<number | string>;
  h?: StyleProp<number | string>;
  maw?: StyleProp<number | string>;
  mah?: StyleProp<number | string>;
  miw?: StyleProp<number | string>;
  mih?: StyleProp<number | string>;
  flex?: StyleProp<CSSProperties['flex']>;
  align?: StyleProp<CSSProperties['alignItems']>;
  justify?: StyleProp<CSSProperties['justifyContent']>;
};
