name: Publish Package

on:
  push:
    tags:
      - '*.*.*'

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.12.2'
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: yarn install

      # Validate tag and version
      - name: Validate tag matches package.json version
        id: validate_version
        working-directory: packages/next
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          TAG_VERSION=$(basename ${GITHUB_REF})
          echo "Package.json version: $PACKAGE_VERSION"
          echo "Tag version: $TAG_VERSION"
          if [ "$PACKAGE_VERSION" != "$TAG_VERSION" ]; then
            echo "Error: Tag version ($TAG_VERSION) does not match package.json version ($PACKAGE_VERSION)"
            exit 1
          fi

      # Debug NPM Token
      - name: Debug NPM Token
        run: |
          if [ -z "${{ env.NPM_TOKEN }}" ]; then
            echo "NPM_TOKEN is not set or empty."
            exit 1
          else
            echo "NPM_TOKEN is set. Length: ${#NPM_TOKEN}"
          fi

      # Create .npmrc for authentication
      - name: Create .npmrc
        working-directory: packages/next
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ env.NPM_TOKEN }}" > .npmrc

      # Build Packages
      - name: Build pakcage
        working-directory: packages/next
        run: yarn build

      # Publish to npm
      - name: Publish to npm
        working-directory: packages/next
        env:
          NODE_AUTH_TOKEN: ${{ env.NPM_TOKEN }}
        run: |
          echo "Publishing package version $TAG_VERSION to npm..."
          npm publish --access public --tag latest
