name: Publish Package

on:
  push:
    tags:
      - '*.*.*'

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.12.2'
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: yarn install

      # Validate tag and version
      - name: Validate tag matches package.json version
        id: validate_version
        working-directory: packages/next
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          TAG_VERSION=$(basename ${GITHUB_REF})
          echo "Package.json version: $PACKAGE_VERSION"
          echo "Tag version: $TAG_VERSION"
          if [ "$PACKAGE_VERSION" != "$TAG_VERSION" ]; then
            echo "Error: Tag version ($TAG_VERSION) does not match package.json version ($PACKAGE_VERSION)"
            exit 1
          fi

      # Build Packages
      - name: Build package
        working-directory: packages/next
        run: yarn build

      # Whoami to verify authentication
      - name: Whoami
        working-directory: packages/next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm whoami

      # Publish to npm
      - name: Publish to npm
        working-directory: packages/next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public --tag latest
